export interface SelectOption {
  value: string;
  label: string;
}

export const INTEREST_OPTIONS: SelectOption[] = [
  // Creative & Arts
  { value: 'art', label: 'INTERESTS.ART' },
  { value: 'crafts', label: 'INTERESTS.CRAFTS' },
  { value: 'dancing', label: 'INTERESTS.DANCING' },
  { value: 'drawing', label: 'INTERESTS.DRAWING' },
  { value: 'music', label: 'INTERESTS.MUSIC' },
  { value: 'painting', label: 'INTERESTS.PAINTING' },
  { value: 'photography', label: 'INTERESTS.PHOTOGRAPHY' },
  { value: 'sculpture', label: 'INTERESTS.SCULPTURE' },
  { value: 'singing', label: 'INTERESTS.SINGING' },
  { value: 'theater', label: 'INTERESTS.THEATER' },
  { value: 'writing', label: 'INTERESTS.WRITING' },

  // Food & Cooking
  { value: 'baking', label: 'INTERESTS.BAKING' },
  { value: 'brewing', label: 'INTERESTS.BREWING' },
  { value: 'cooking', label: 'INTERESTS.COOKING' },
  { value: 'wine-tasting', label: 'INTERESTS.WINE_TASTING' },

  // Sports & Fitness
  { value: 'basketball', label: 'INTERESTS.BASKETBALL' },
  { value: 'boxing', label: 'INTERESTS.BOXING' },
  { value: 'cycling', label: 'INTERESTS.CYCLING' },
  { value: 'fitness', label: 'INTERESTS.FITNESS' },
  { value: 'football', label: 'INTERESTS.FOOTBALL' },
  { value: 'golf', label: 'INTERESTS.GOLF' },
  { value: 'hiking', label: 'INTERESTS.HIKING' },
  { value: 'martial-arts', label: 'INTERESTS.MARTIAL_ARTS' },
  { value: 'rock-climbing', label: 'INTERESTS.ROCK_CLIMBING' },
  { value: 'running', label: 'INTERESTS.RUNNING' },
  { value: 'skiing', label: 'INTERESTS.SKIING' },
  { value: 'soccer', label: 'INTERESTS.SOCCER' },
  { value: 'swimming', label: 'INTERESTS.SWIMMING' },
  { value: 'tennis', label: 'INTERESTS.TENNIS' },
  { value: 'volleyball', label: 'INTERESTS.VOLLEYBALL' },
  { value: 'yoga', label: 'INTERESTS.YOGA' },

  // Technology & Gaming
  { value: 'coding', label: 'INTERESTS.CODING' },
  { value: 'gaming', label: 'INTERESTS.GAMING' },
  { value: 'robotics', label: 'INTERESTS.ROBOTICS' },
  { value: 'technology', label: 'INTERESTS.TECHNOLOGY' },
  { value: 'web-design', label: 'INTERESTS.WEB_DESIGN' },

  // Outdoor & Nature
  { value: 'astronomy', label: 'INTERESTS.ASTRONOMY' },
  { value: 'camping', label: 'INTERESTS.CAMPING' },
  { value: 'fishing', label: 'INTERESTS.FISHING' },
  { value: 'gardening', label: 'INTERESTS.GARDENING' },
  { value: 'hunting', label: 'INTERESTS.HUNTING' },
  { value: 'nature-watching', label: 'INTERESTS.NATURE_WATCHING' },

  // Entertainment & Media
  { value: 'anime', label: 'INTERESTS.ANIME' },
  { value: 'movies', label: 'INTERESTS.MOVIES' },
  { value: 'podcasts', label: 'INTERESTS.PODCASTS' },
  { value: 'tv-shows', label: 'INTERESTS.TV_SHOWS' },

  // Learning & Culture
  { value: 'history', label: 'INTERESTS.HISTORY' },
  { value: 'languages', label: 'INTERESTS.LANGUAGES' },
  { value: 'philosophy', label: 'INTERESTS.PHILOSOPHY' },
  { value: 'psychology', label: 'INTERESTS.PSYCHOLOGY' },
  { value: 'reading', label: 'INTERESTS.READING' },
  { value: 'science', label: 'INTERESTS.SCIENCE' },

  // Social & Community
  { value: 'networking', label: 'INTERESTS.NETWORKING' },
  { value: 'volunteering', label: 'INTERESTS.VOLUNTEERING' },

  // Travel & Adventure
  { value: 'backpacking', label: 'INTERESTS.BACKPACKING' },
  { value: 'traveling', label: 'INTERESTS.TRAVELING' },

  // Hobbies & Crafts
  { value: 'board-games', label: 'INTERESTS.BOARD_GAMES' },
  { value: 'chess', label: 'INTERESTS.CHESS' },
  { value: 'collecting', label: 'INTERESTS.COLLECTING' },
  { value: 'diy', label: 'INTERESTS.DIY' },
  { value: 'knitting', label: 'INTERESTS.KNITTING' },
  { value: 'puzzles', label: 'INTERESTS.PUZZLES' },
  { value: 'woodworking', label: 'INTERESTS.WOODWORKING' },

  // Music & Instruments
  { value: 'guitar', label: 'INTERESTS.GUITAR' },
  { value: 'piano', label: 'INTERESTS.PIANO' },
  { value: 'drums', label: 'INTERESTS.DRUMS' },

  // Fashion & Beauty
  { value: 'fashion', label: 'INTERESTS.FASHION' },
  { value: 'makeup', label: 'INTERESTS.MAKEUP' },

  // Business & Finance
  { value: 'investing', label: 'INTERESTS.INVESTING' },
  { value: 'entrepreneurship', label: 'INTERESTS.ENTREPRENEURSHIP' },
];

export const LANGUAGE_OPTIONS: SelectOption[] = [
  // Major World Languages
  { value: 'arabic', label: 'LANGUAGES.ARABIC' },
  { value: 'bengali', label: 'LANGUAGES.BENGALI' },
  { value: 'chinese-mandarin', label: 'LANGUAGES.CHINESE_MANDARIN' },
  { value: 'chinese-cantonese', label: 'LANGUAGES.CHINESE_CANTONESE' },
  { value: 'english', label: 'LANGUAGES.ENGLISH' },
  { value: 'french', label: 'LANGUAGES.FRENCH' },
  { value: 'german', label: 'LANGUAGES.GERMAN' },
  { value: 'hindi', label: 'LANGUAGES.HINDI' },
  { value: 'indonesian', label: 'LANGUAGES.INDONESIAN' },
  { value: 'italian', label: 'LANGUAGES.ITALIAN' },
  { value: 'japanese', label: 'LANGUAGES.JAPANESE' },
  { value: 'korean', label: 'LANGUAGES.KOREAN' },
  { value: 'portuguese', label: 'LANGUAGES.PORTUGUESE' },
  { value: 'russian', label: 'LANGUAGES.RUSSIAN' },
  { value: 'spanish', label: 'LANGUAGES.SPANISH' },
  { value: 'turkish', label: 'LANGUAGES.TURKISH' },
  { value: 'urdu', label: 'LANGUAGES.URDU' },
  { value: 'vietnamese', label: 'LANGUAGES.VIETNAMESE' },

  // European Languages
  { value: 'albanian', label: 'LANGUAGES.ALBANIAN' },
  { value: 'basque', label: 'LANGUAGES.BASQUE' },
  { value: 'belarusian', label: 'LANGUAGES.BELARUSIAN' },
  { value: 'bosnian', label: 'LANGUAGES.BOSNIAN' },
  { value: 'bulgarian', label: 'LANGUAGES.BULGARIAN' },
  { value: 'catalan', label: 'LANGUAGES.CATALAN' },
  { value: 'croatian', label: 'LANGUAGES.CROATIAN' },
  { value: 'czech', label: 'LANGUAGES.CZECH' },
  { value: 'danish', label: 'LANGUAGES.DANISH' },
  { value: 'dutch', label: 'LANGUAGES.DUTCH' },
  { value: 'estonian', label: 'LANGUAGES.ESTONIAN' },
  { value: 'finnish', label: 'LANGUAGES.FINNISH' },
  { value: 'galician', label: 'LANGUAGES.GALICIAN' },
  { value: 'greek', label: 'LANGUAGES.GREEK' },
  { value: 'hungarian', label: 'LANGUAGES.HUNGARIAN' },
  { value: 'icelandic', label: 'LANGUAGES.ICELANDIC' },
  { value: 'irish', label: 'LANGUAGES.IRISH' },
  { value: 'latvian', label: 'LANGUAGES.LATVIAN' },
  { value: 'lithuanian', label: 'LANGUAGES.LITHUANIAN' },
  { value: 'macedonian', label: 'LANGUAGES.MACEDONIAN' },
  { value: 'maltese', label: 'LANGUAGES.MALTESE' },
  { value: 'norwegian', label: 'LANGUAGES.NORWEGIAN' },
  { value: 'polish', label: 'LANGUAGES.POLISH' },
  { value: 'romanian', label: 'LANGUAGES.ROMANIAN' },
  { value: 'serbian', label: 'LANGUAGES.SERBIAN' },
  { value: 'slovak', label: 'LANGUAGES.SLOVAK' },
  { value: 'slovenian', label: 'LANGUAGES.SLOVENIAN' },
  { value: 'swedish', label: 'LANGUAGES.SWEDISH' },
  { value: 'ukrainian', label: 'LANGUAGES.UKRAINIAN' },
  { value: 'welsh', label: 'LANGUAGES.WELSH' },

  // African Languages
  { value: 'afrikaans', label: 'LANGUAGES.AFRIKAANS' },
  { value: 'amharic', label: 'LANGUAGES.AMHARIC' },
  { value: 'hausa', label: 'LANGUAGES.HAUSA' },
  { value: 'swahili', label: 'LANGUAGES.SWAHILI' },
  { value: 'yoruba', label: 'LANGUAGES.YORUBA' },
  { value: 'zulu', label: 'LANGUAGES.ZULU' },

  // Asian Languages
  { value: 'burmese', label: 'LANGUAGES.BURMESE' },
  { value: 'khmer', label: 'LANGUAGES.KHMER' },
  { value: 'lao', label: 'LANGUAGES.LAO' },
  { value: 'malay', label: 'LANGUAGES.MALAY' },
  { value: 'mongolian', label: 'LANGUAGES.MONGOLIAN' },
  { value: 'nepali', label: 'LANGUAGES.NEPALI' },
  { value: 'punjabi', label: 'LANGUAGES.PUNJABI' },
  { value: 'sinhala', label: 'LANGUAGES.SINHALA' },
  { value: 'tagalog', label: 'LANGUAGES.TAGALOG' },
  { value: 'tamil', label: 'LANGUAGES.TAMIL' },
  { value: 'thai', label: 'LANGUAGES.THAI' },
  { value: 'tibetan', label: 'LANGUAGES.TIBETAN' },

  // Middle Eastern Languages
  { value: 'armenian', label: 'LANGUAGES.ARMENIAN' },
  { value: 'azerbaijani', label: 'LANGUAGES.AZERBAIJANI' },
  { value: 'georgian', label: 'LANGUAGES.GEORGIAN' },
  { value: 'hebrew', label: 'LANGUAGES.HEBREW' },
  { value: 'kazakh', label: 'LANGUAGES.KAZAKH' },
  { value: 'kurdish', label: 'LANGUAGES.KURDISH' },
  { value: 'persian', label: 'LANGUAGES.PERSIAN' },
  { value: 'uzbek', label: 'LANGUAGES.UZBEK' },

  // Other Languages
  { value: 'esperanto', label: 'LANGUAGES.ESPERANTO' },
  { value: 'latin', label: 'LANGUAGES.LATIN' },
];

export const COUNTRY_OPTIONS: SelectOption[] = [
  { value: 'afghanistan', label: 'COUNTRIES.AFGHANISTAN' },
  { value: 'albania', label: 'COUNTRIES.ALBANIA' },
  { value: 'algeria', label: 'COUNTRIES.ALGERIA' },
  { value: 'andorra', label: 'COUNTRIES.ANDORRA' },
  { value: 'angola', label: 'COUNTRIES.ANGOLA' },
  { value: 'antigua-and-barbuda', label: 'COUNTRIES.ANTIGUA_AND_BARBUDA' },
  { value: 'argentina', label: 'COUNTRIES.ARGENTINA' },
  { value: 'armenia', label: 'COUNTRIES.ARMENIA' },
  { value: 'australia', label: 'COUNTRIES.AUSTRALIA' },
  { value: 'austria', label: 'COUNTRIES.AUSTRIA' },
  { value: 'azerbaijan', label: 'COUNTRIES.AZERBAIJAN' },
  { value: 'bahamas', label: 'COUNTRIES.BAHAMAS' },
  { value: 'bahrain', label: 'COUNTRIES.BAHRAIN' },
  { value: 'bangladesh', label: 'COUNTRIES.BANGLADESH' },
  { value: 'barbados', label: 'COUNTRIES.BARBADOS' },
  { value: 'belarus', label: 'COUNTRIES.BELARUS' },
  { value: 'belgium', label: 'COUNTRIES.BELGIUM' },
  { value: 'belize', label: 'COUNTRIES.BELIZE' },
  { value: 'benin', label: 'COUNTRIES.BENIN' },
  { value: 'bhutan', label: 'COUNTRIES.BHUTAN' },
  { value: 'bolivia', label: 'COUNTRIES.BOLIVIA' },
  { value: 'bosnia-and-herzegovina', label: 'COUNTRIES.BOSNIA_AND_HERZEGOVINA' },
  { value: 'botswana', label: 'COUNTRIES.BOTSWANA' },
  { value: 'brazil', label: 'COUNTRIES.BRAZIL' },
  { value: 'brunei', label: 'COUNTRIES.BRUNEI' },
  { value: 'bulgaria', label: 'COUNTRIES.BULGARIA' },
  { value: 'burkina-faso', label: 'COUNTRIES.BURKINA_FASO' },
  { value: 'burundi', label: 'COUNTRIES.BURUNDI' },
  { value: 'cambodia', label: 'COUNTRIES.CAMBODIA' },
  { value: 'cameroon', label: 'COUNTRIES.CAMEROON' },
  { value: 'canada', label: 'COUNTRIES.CANADA' },
  { value: 'cape-verde', label: 'COUNTRIES.CAPE_VERDE' },
  { value: 'central-african-republic', label: 'COUNTRIES.CENTRAL_AFRICAN_REPUBLIC' },
  { value: 'chad', label: 'COUNTRIES.CHAD' },
  { value: 'chile', label: 'COUNTRIES.CHILE' },
  { value: 'china', label: 'COUNTRIES.CHINA' },
  { value: 'colombia', label: 'COUNTRIES.COLOMBIA' },
  { value: 'comoros', label: 'COUNTRIES.COMOROS' },
  { value: 'congo-democratic-republic', label: 'COUNTRIES.CONGO_DEMOCRATIC_REPUBLIC' },
  { value: 'congo-republic', label: 'COUNTRIES.CONGO_REPUBLIC' },
  { value: 'costa-rica', label: 'COUNTRIES.COSTA_RICA' },
  { value: 'croatia', label: 'COUNTRIES.CROATIA' },
  { value: 'cuba', label: 'COUNTRIES.CUBA' },
  { value: 'cyprus', label: 'COUNTRIES.CYPRUS' },
  { value: 'czech-republic', label: 'COUNTRIES.CZECH_REPUBLIC' },
  { value: 'denmark', label: 'COUNTRIES.DENMARK' },
  { value: 'djibouti', label: 'COUNTRIES.DJIBOUTI' },
  { value: 'dominica', label: 'COUNTRIES.DOMINICA' },
  { value: 'dominican-republic', label: 'COUNTRIES.DOMINICAN_REPUBLIC' },
  { value: 'ecuador', label: 'COUNTRIES.ECUADOR' },
  { value: 'egypt', label: 'COUNTRIES.EGYPT' },
  { value: 'el-salvador', label: 'COUNTRIES.EL_SALVADOR' },
  { value: 'equatorial-guinea', label: 'COUNTRIES.EQUATORIAL_GUINEA' },
  { value: 'eritrea', label: 'COUNTRIES.ERITREA' },
  { value: 'estonia', label: 'COUNTRIES.ESTONIA' },
  { value: 'eswatini', label: 'COUNTRIES.ESWATINI' },
  { value: 'ethiopia', label: 'COUNTRIES.ETHIOPIA' },
  { value: 'fiji', label: 'COUNTRIES.FIJI' },
  { value: 'finland', label: 'COUNTRIES.FINLAND' },
  { value: 'france', label: 'COUNTRIES.FRANCE' },
  { value: 'gabon', label: 'COUNTRIES.GABON' },
  { value: 'gambia', label: 'COUNTRIES.GAMBIA' },
  { value: 'georgia', label: 'COUNTRIES.GEORGIA' },
  { value: 'germany', label: 'COUNTRIES.GERMANY' },
  { value: 'ghana', label: 'COUNTRIES.GHANA' },
  { value: 'greece', label: 'COUNTRIES.GREECE' },
  { value: 'grenada', label: 'COUNTRIES.GRENADA' },
  { value: 'guatemala', label: 'COUNTRIES.GUATEMALA' },
  { value: 'guinea', label: 'COUNTRIES.GUINEA' },
  { value: 'guinea-bissau', label: 'COUNTRIES.GUINEA_BISSAU' },
  { value: 'guyana', label: 'COUNTRIES.GUYANA' },
  { value: 'haiti', label: 'COUNTRIES.HAITI' },
  { value: 'honduras', label: 'COUNTRIES.HONDURAS' },
  { value: 'hungary', label: 'COUNTRIES.HUNGARY' },
  { value: 'iceland', label: 'COUNTRIES.ICELAND' },
  { value: 'india', label: 'COUNTRIES.INDIA' },
  { value: 'indonesia', label: 'COUNTRIES.INDONESIA' },
  { value: 'iran', label: 'COUNTRIES.IRAN' },
  { value: 'iraq', label: 'COUNTRIES.IRAQ' },
  { value: 'ireland', label: 'COUNTRIES.IRELAND' },
  { value: 'israel', label: 'COUNTRIES.ISRAEL' },
  { value: 'italy', label: 'COUNTRIES.ITALY' },
  { value: 'ivory-coast', label: 'COUNTRIES.IVORY_COAST' },
  { value: 'jamaica', label: 'COUNTRIES.JAMAICA' },
  { value: 'japan', label: 'COUNTRIES.JAPAN' },
  { value: 'jordan', label: 'COUNTRIES.JORDAN' },
  { value: 'kazakhstan', label: 'COUNTRIES.KAZAKHSTAN' },
  { value: 'kenya', label: 'COUNTRIES.KENYA' },
  { value: 'kiribati', label: 'COUNTRIES.KIRIBATI' },
  { value: 'kosovo', label: 'COUNTRIES.KOSOVO' },
  { value: 'kuwait', label: 'COUNTRIES.KUWAIT' },
  { value: 'kyrgyzstan', label: 'COUNTRIES.KYRGYZSTAN' },
  { value: 'laos', label: 'COUNTRIES.LAOS' },
  { value: 'latvia', label: 'COUNTRIES.LATVIA' },
  { value: 'lebanon', label: 'COUNTRIES.LEBANON' },
  { value: 'lesotho', label: 'COUNTRIES.LESOTHO' },
  { value: 'liberia', label: 'COUNTRIES.LIBERIA' },
  { value: 'libya', label: 'COUNTRIES.LIBYA' },
  { value: 'liechtenstein', label: 'COUNTRIES.LIECHTENSTEIN' },
  { value: 'lithuania', label: 'COUNTRIES.LITHUANIA' },
  { value: 'luxembourg', label: 'COUNTRIES.LUXEMBOURG' },
  { value: 'madagascar', label: 'COUNTRIES.MADAGASCAR' },
  { value: 'malawi', label: 'COUNTRIES.MALAWI' },
  { value: 'malaysia', label: 'COUNTRIES.MALAYSIA' },
  { value: 'maldives', label: 'COUNTRIES.MALDIVES' },
  { value: 'mali', label: 'COUNTRIES.MALI' },
  { value: 'malta', label: 'COUNTRIES.MALTA' },
  { value: 'marshall-islands', label: 'COUNTRIES.MARSHALL_ISLANDS' },
  { value: 'mauritania', label: 'COUNTRIES.MAURITANIA' },
  { value: 'mauritius', label: 'COUNTRIES.MAURITIUS' },
  { value: 'mexico', label: 'COUNTRIES.MEXICO' },
  { value: 'micronesia', label: 'COUNTRIES.MICRONESIA' },
  { value: 'moldova', label: 'COUNTRIES.MOLDOVA' },
  { value: 'monaco', label: 'COUNTRIES.MONACO' },
  { value: 'mongolia', label: 'COUNTRIES.MONGOLIA' },
  { value: 'montenegro', label: 'COUNTRIES.MONTENEGRO' },
  { value: 'morocco', label: 'COUNTRIES.MOROCCO' },
  { value: 'mozambique', label: 'COUNTRIES.MOZAMBIQUE' },
  { value: 'myanmar', label: 'COUNTRIES.MYANMAR' },
  { value: 'namibia', label: 'COUNTRIES.NAMIBIA' },
  { value: 'nauru', label: 'COUNTRIES.NAURU' },
  { value: 'nepal', label: 'COUNTRIES.NEPAL' },
  { value: 'netherlands', label: 'COUNTRIES.NETHERLANDS' },
  { value: 'new-zealand', label: 'COUNTRIES.NEW_ZEALAND' },
  { value: 'nicaragua', label: 'COUNTRIES.NICARAGUA' },
  { value: 'niger', label: 'COUNTRIES.NIGER' },
  { value: 'nigeria', label: 'COUNTRIES.NIGERIA' },
  { value: 'north-korea', label: 'COUNTRIES.NORTH_KOREA' },
  { value: 'north-macedonia', label: 'COUNTRIES.NORTH_MACEDONIA' },
  { value: 'norway', label: 'COUNTRIES.NORWAY' },
  { value: 'oman', label: 'COUNTRIES.OMAN' },
  { value: 'pakistan', label: 'COUNTRIES.PAKISTAN' },
  { value: 'palau', label: 'COUNTRIES.PALAU' },
  { value: 'palestine', label: 'COUNTRIES.PALESTINE' },
  { value: 'panama', label: 'COUNTRIES.PANAMA' },
  { value: 'papua-new-guinea', label: 'COUNTRIES.PAPUA_NEW_GUINEA' },
  { value: 'paraguay', label: 'COUNTRIES.PARAGUAY' },
  { value: 'peru', label: 'COUNTRIES.PERU' },
  { value: 'philippines', label: 'COUNTRIES.PHILIPPINES' },
  { value: 'poland', label: 'COUNTRIES.POLAND' },
  { value: 'portugal', label: 'COUNTRIES.PORTUGAL' },
  { value: 'qatar', label: 'COUNTRIES.QATAR' },
  { value: 'romania', label: 'COUNTRIES.ROMANIA' },
  { value: 'russia', label: 'COUNTRIES.RUSSIA' },
  { value: 'rwanda', label: 'COUNTRIES.RWANDA' },
  { value: 'saint-kitts-and-nevis', label: 'COUNTRIES.SAINT_KITTS_AND_NEVIS' },
  { value: 'saint-lucia', label: 'COUNTRIES.SAINT_LUCIA' },
  { value: 'saint-vincent-and-grenadines', label: 'COUNTRIES.SAINT_VINCENT_AND_GRENADINES' },
  { value: 'samoa', label: 'COUNTRIES.SAMOA' },
  { value: 'san-marino', label: 'COUNTRIES.SAN_MARINO' },
  { value: 'sao-tome-and-principe', label: 'COUNTRIES.SAO_TOME_AND_PRINCIPE' },
  { value: 'saudi-arabia', label: 'COUNTRIES.SAUDI_ARABIA' },
  { value: 'senegal', label: 'COUNTRIES.SENEGAL' },
  { value: 'serbia', label: 'COUNTRIES.SERBIA' },
  { value: 'seychelles', label: 'COUNTRIES.SEYCHELLES' },
  { value: 'sierra-leone', label: 'COUNTRIES.SIERRA_LEONE' },
  { value: 'singapore', label: 'COUNTRIES.SINGAPORE' },
  { value: 'slovakia', label: 'COUNTRIES.SLOVAKIA' },
  { value: 'slovenia', label: 'COUNTRIES.SLOVENIA' },
  { value: 'solomon-islands', label: 'COUNTRIES.SOLOMON_ISLANDS' },
  { value: 'somalia', label: 'COUNTRIES.SOMALIA' },
  { value: 'south-africa', label: 'COUNTRIES.SOUTH_AFRICA' },
  { value: 'south-korea', label: 'COUNTRIES.SOUTH_KOREA' },
  { value: 'south-sudan', label: 'COUNTRIES.SOUTH_SUDAN' },
  { value: 'spain', label: 'COUNTRIES.SPAIN' },
  { value: 'sri-lanka', label: 'COUNTRIES.SRI_LANKA' },
  { value: 'sudan', label: 'COUNTRIES.SUDAN' },
  { value: 'suriname', label: 'COUNTRIES.SURINAME' },
  { value: 'sweden', label: 'COUNTRIES.SWEDEN' },
  { value: 'switzerland', label: 'COUNTRIES.SWITZERLAND' },
  { value: 'syria', label: 'COUNTRIES.SYRIA' },
  { value: 'taiwan', label: 'COUNTRIES.TAIWAN' },
  { value: 'tajikistan', label: 'COUNTRIES.TAJIKISTAN' },
  { value: 'tanzania', label: 'COUNTRIES.TANZANIA' },
  { value: 'thailand', label: 'COUNTRIES.THAILAND' },
  { value: 'timor-leste', label: 'COUNTRIES.TIMOR_LESTE' },
  { value: 'togo', label: 'COUNTRIES.TOGO' },
  { value: 'tonga', label: 'COUNTRIES.TONGA' },
  { value: 'trinidad-and-tobago', label: 'COUNTRIES.TRINIDAD_AND_TOBAGO' },
  { value: 'tunisia', label: 'COUNTRIES.TUNISIA' },
  { value: 'turkey', label: 'COUNTRIES.TURKEY' },
  { value: 'turkmenistan', label: 'COUNTRIES.TURKMENISTAN' },
  { value: 'tuvalu', label: 'COUNTRIES.TUVALU' },
  { value: 'uganda', label: 'COUNTRIES.UGANDA' },
  { value: 'ukraine', label: 'COUNTRIES.UKRAINE' },
  { value: 'united-arab-emirates', label: 'COUNTRIES.UNITED_ARAB_EMIRATES' },
  { value: 'united-kingdom', label: 'COUNTRIES.UNITED_KINGDOM' },
  { value: 'united-states', label: 'COUNTRIES.UNITED_STATES' },
  { value: 'uruguay', label: 'COUNTRIES.URUGUAY' },
  { value: 'uzbekistan', label: 'COUNTRIES.UZBEKISTAN' },
  { value: 'vanuatu', label: 'COUNTRIES.VANUATU' },
  { value: 'vatican-city', label: 'COUNTRIES.VATICAN_CITY' },
  { value: 'venezuela', label: 'COUNTRIES.VENEZUELA' },
  { value: 'vietnam', label: 'COUNTRIES.VIETNAM' },
  { value: 'yemen', label: 'COUNTRIES.YEMEN' },
  { value: 'zambia', label: 'COUNTRIES.ZAMBIA' },
  { value: 'zimbabwe', label: 'COUNTRIES.ZIMBABWE' },
];
